name: Apply terraform changes

on:
  push:
    branches:
      - main
      - stg
    paths:
      - project/**

env:
  TF_WORKSPACES_MAPPING: '{ "main": "prod", "stg": "stg" }'
  CACHE_DIRECTORY: .terraform.d/plugin-cache
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  tf-apply:
    name: Terraform apply
    runs-on: ubuntu-latest

    steps:
      - name: Add TF_WORKSPACE to env
        run: echo "WORKSPACE=${{ fromJson(env.TF_WORKSPACES_MAPPING)[github.ref_name] }}" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v3

      - name: Create terraform plugin cache directory
        run: mkdir --parents ${{ env.CACHE_DIRECTORY }}

      - name: Cache terraform plugin cache directory
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_DIRECTORY }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: ${{ runner.os }}-terraform-

      - name: Terraform apply
        uses: aklyukin/tf-gha/terraform-apply@main
        with:
          path: project
          workspace: ${{ env.WORKSPACE }}
          plugin_cache_dir: /github/workspace/${{ env.CACHE_DIRECTORY }}
          var_files: ${{ env.WORKSPACE }}.tfvars