name: Build Images and Deploy

on:
  push:
    branches:
      - issue-1

env:
  TF_WORKSPACES_MAPPING: '{ "main": "prod", "issue-1": "stg" }'

jobs:

  build:
    name: Build Images and Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:

      - name: Print tf_workspace
        run: echo "TF_WORKSPACE=${{ fromJson(env.TF_WORKSPACES_MAPPING)[github.ref_name] }}" >> $GITHUB_ENV

      - name: Print tf_workspace
        run: echo "${{ env.TF_WORKSPACE }}"

      - name: Check out code
        uses: actions/checkout@v3

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#      - name: terraform apply
#        uses: aklyukin/tf-gha/terraform-plan@main
#        with:
#          path: project
#          tf_workspace: ${{ tf_workspace }}
#          varsfile: ${{ tf_workspace }}.tfvars