name: Build Images and Deploy

on:
  push:
    branches:
      - issue-1

env:
  TF_WORKSPACES_MAPPING: '{ "main": "prod", "issue-1": "stg" }'

jobs:

  build:
    name: Build Images and Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:

      - name: Add TF_WORKSPACE to env
        run: echo "WORKSPACE=${{ fromJson(env.TF_WORKSPACES_MAPPING)[github.ref_name] }}" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v3

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: terraform apply
        uses: aklyukin/tf-gha/terraform-plan@main
        with:
          path: project
          workspace: ${{ env.WORKSPACE }}
          var_files: ${{ tf_workspace }}.tfvars